### ISSUE TITLE
Some errors when trying to use the plugin

### ISSUE THREAD

**Issue by 1Lucas1apk** [DRSchlaubi/lyrics.kt#1]
Hello, today I was making some codes to support a plugin, but there are some things that aren't working correctly, I think with Lyrics.kt

(sessions/{sessionId}/players/guildId/lyrics)

```js
{
  timestamp: 1703985314125,
  status: 404,
  error: 'Not Found',
  message: 'Not Found',
  path: '/v4/sessions/.../players/.../lyrics'
} 
```

It gives this error for any song that is playing in the player

(lyrics/search/{args})
```js
[
  {
    videoId: 'PZqLVs7m9jo',
    title: 'nesta casa não existem fantasmas, são puras lembranças... ( legendado) { tradução }'
  },
  {
    videoId: '3AgxhgVMt9o',
    title: 'En Esta Casa No Existen Fantasmas Solo Recuerdos'
  },
  { videoId: 'UsaLBzY8S3M', title: 'Lei da Vida' },
  { videoId: 'hqX42B0f8Hk', title: 'Lei da Vida pt. 2' }
] 
```
So far it seems to be working, but sometimes if you use the videoId with (lyrics/{videoId}) it says it doesn't exist
```js
{
  timestamp: 1703985454849,
  status: 404,
  error: 'Not Found',
  message: 'Not Found',
  path: '/v4/lyrics/PZqLVs7m9jo'
} 
```

- [x] I'm using lavalink in the latest stable version

**Comment by DRSchlaubi** [comment]
that means, that the lyrics don't exist, not all videoIds returned by search work, since the search endpoint used, does not have that information and checking it would require 2 tracks per result, so very easy rate limit

**Comment by 1Lucas1apk** [comment]
I understood
