### ISSUE TITLE
Lyrics Not Found

### ISSUE THREAD

**Issue by SCARTAL** [DRSchlaubi/lyrics.kt#8]
whenever I try to get a lyric using a GET request to `/v4/sessions/SESSION_ID/players/GUILD_ID/lyrics` I receive response code 404.

I tried it with different songs (famous songs) but the response remains 404 and the plugin fails to fetch the lyrics.

**Comment by DRSchlaubi** [comment]
Did you check whether the video you queued has lyrics on music.youtube.com

**Comment by SCARTAL** [comment]
One of my test tracks was bad guy by billie eillish which has lyrics in music.youtube.com

**Comment by DRSchlaubi** [comment]
Often there is a difference between the music video and the youtube music audio version, so if you go to music.youtube.com/watch?v={id from lavalink} does it have lyrics

**Comment by SCARTAL** [comment]
Yes, this is one of the tracks that I have played and got 404

https://music.youtube.com/watch?v=DyDfgMOUjCI

**Comment by DRSchlaubi** [comment]
> Yes, this is one of the tracks that I have played and got 404
> 
> https://music.youtube.com/watch?v=DyDfgMOUjCI

Try playing https://music.youtube.com/watch?v=ZD6rXLXZOEI

**Comment by SCARTAL** [comment]
it worked, so if I want to have a better chance of getting a track lyrics I should try search it to get a valid ID which contains lyrics ?

**Comment by DRSchlaubi** [comment]
Either that or directly use the search endpoint, since the video id only works if that video has lyrics
