### ISSUE TITLE
text property 

### ISSUE THREAD

**Issue by luomodev** [DRSchlaubi/lyrics.kt#9]
`{
  type: 'timed',
  track: {
    title: 'Please Please Please',
    author: 'Sabrina Carpenter',
    album: "Short n' Sweet",
    albumArt: [ [Object], [Object], [Object], [Object], [Object], [Object] ]
  },
  source: 'LyricFind',
  lines: [
    { line: '♪', range: [Object] },
    {
      line: 'I know I have good judgment, I know I have good taste',
      range: [Object]
    },
    {
      line: "It's funny and it's ironic that only I feel that way",
      range: [Object]
    },
    {
      line: "I promise 'em that you're different and everyone makes mistakes",
      range: [Object]
    },
    { line: "But just don't", range: [Object] },
    {
      line: "I heard that you're an actor, so act like a stand-up guy",
      range: [Object]
    },
    {
      line: "Whatever devil's inside you, don't let him out tonight",
      range: [Object]
    },
    {
      line: "I tell them it's just your culture and everyone rolls their eyes",
      range: [Object]
    },
    { line: 'Yeah, I know', range: [Object] },
    { line: "All I'm asking, baby", range: [Object] },
    { line: 'Please, please, please', range: [Object] },
    { line: "Don't prove I'm right", range: [Object] },
    { line: 'And please, please, please', range: [Object] },
    {
      line: "Don't bring me to tears when I just did my makeup so nice",
      range: [Object]
    },
    {
      line: "Heartbreak is one thing, my ego's another",
      range: [Object]
    },
    {
      line: "I beg you, don't embarrass me, motherfucker",
      range: [Object]
    },
    { line: 'Ah, oh', range: [Object] },
    { line: 'Please, please, please (ah, ah, ah)', range: [Object] },
    {
      line: 'Well, I have a fun idea, babe (uh-huh), maybe just stay inside',
      range: [Object]
    },
    {
      line: "I know you're craving some fresh air, but the ceiling fan is so nice (it's so nice, right?)",
      range: [Object]
    },
    {
      line: "And we could live so happily if no one knows that you're with me",
      range: [Object]
    },
    {
      line: "I'm just kidding, but really (kinda), really, really",
      range: [Object]
    },
    {
      line: "Please, please, please (please don't prove I'm right)",
      range: [Object]
    },
    { line: "Don't prove I'm right", range: [Object] },
    { line: 'And please, please, please', range: [Object] },
    {
      line: "Don't bring me to tears when I just did my makeup so nice",
      range: [Object]
    },
    {
      line: "Heartbreak is one thing (heartbreak is one thing), my ego's another (ego's another)",
      range: [Object]
    },
    {
      line: "I beg you, don't embarrass me, motherfucker",
      range: [Object]
    },
    { line: 'Ah, oh', range: [Object] },
    { line: 'Please, please, please (ah, ah, ah)', range: [Object] },
    { line: 'If you wanna go and be stupid', range: [Object] },
    { line: "Don't do it in front of me", range: [Object] },
    { line: "If you don't wanna cry to my music", range: [Object] },
    { line: "Don't make me hate you prolifically", range: [Object] },
    { line: 'Please, please, please (please)', range: [Object] },
    { line: 'Please, please, please (please)', range: [Object] },
    {
      line: 'Please (please), please (please), please',
      range: [Object]
    },
    { line: '(Ah)', range: [Object] }
  ]
}

**Comment by luomodev** [comment]
i printed the result but there isnt the property text, is it removed or i made something wrong?

**Comment by DRSchlaubi** [comment]
text is only present for type text
